<?php
//Filename:  JudgeTESTphpFunctions2013.php
//Author:  Susan Weick
//Date:  December 2012
//Functions include:
//1.  htmlHeader() - beginning html (most generated by FrontPage or Dreamweaver already created by client)
//2.  htmlFooter() - ending html
//2.  logUser($mbrName, $mbrNumber, $mbrEmail, $passFail, $message)
//    -> logs everyone who clicks the submit button the JudgeTestOnlineForm.htm page
//3.  emailLetter($inputNum) - for each number, returns two-letter char string in
//		alphabetical order
//***************************************************************
function htmlHeader(){
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><!-- InstanceBegin template="/Templates/HRCPageTemplate.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- InstanceBeginEditable name="doctitle" -->
<title>Welcome to Hunting Retriever Club, Inc.</title>
<style type="text/css">
.bold {
	font-weight: bold;
}
</style>
<!-- InstanceEndEditable -->
<style type="text/css">
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
	background-color: #6F0202;
	font-family: Arial, Helvetica, sans-serif;
	text-align: left;
}
#apDiv1 {
	position: absolute;
	width: 764px;
	height: 290px;
	z-index: 1;
	left: 429px;
	top: 87px;
}
#BlackBackground {
	background-image: url(images/menubarback_black.gif);
}
.style1 
{	color: #FF0000;
	font-size: small;
}
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" type="text/javascript"></script>
<script type="text/javascript" src="JudgeTESTScriptJQuery.js"></script>
<!-- InstanceBeginEditable name="head" -->
<!-- InstanceEndEditable -->
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="center" bgcolor="#FCCC9E"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="148" align="center" valign="top" id="masthead_table_redandblack"><!--#include file="menubar.shtml" -->
<?php
include("menubar.shtml");
?>
		</td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td height="0" align="center" valign="top" bgcolor="#FCCC9E"><table width="1153" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="22" height="225">&nbsp;</td>
        <td width="283" align="center" valign="top" bgcolor="#E3B382">
			<script language="JavaScript" type="text/javascript"> 
<!-- 
var 
month = new Array(); 
month[0]="January"; 
month[1]="February"; 
month[2]="March"; 
month[3]="April"; 
month[4]="May"; 
month[5]="June"; 
month[6]="July"; 
month[7]="August"; 
month[8]="September"; 
month[9]="October"; 
month[10]="November"; 
month[11]="December"; 
var 
day = new Array(); 
day[0]="Sunday"; 
day[1]="Monday"; 
day[2]="Tuesday"; 
day[3]="Wednesday"; 
day[4]="Thursday"; 
day[5]="Friday"; 
day[6]="Saturday"; 
today = new Date(); 
date = today.getDate(); 
day = (day[today.getDay()]); 
month = (month[today.getMonth()]); 
year = (today.getFullYear()); 
suffix = (date==1 || date==21 || date==31) ? "st" : "th" && 
(date==2 || date==22) ? "nd" : "th" && (date==3 || date==23) ? "rd" : "th" 
function print_date() 
{ 
document.write(day + "," + "&nbsp;" + date + "<sup>" + suffix + "</sup>" + "&nbsp;" +
 month + "," + "&nbsp;" + year); 
} 
// --> 
</script> 
<script type="text/javascript"> 
<!-- 
print_date(); 
//--> 
</script>
<br />
<br />
<!--#include file="sidebar.shtml" -->
<?php
include("sidebar.shtml");
?>
	</td>


        <td width="28" align="left" valign="top">&nbsp;</td>
        <td width="817" align="left" valign="top"><!-- InstanceBeginEditable name="Main Body" -->
<h1><strong>HRC 2013/2014 Judges Test On-line...</strong></h1>
<hr width="100%" />

<?php
} //end htmlHeader function
//**************************************************************************
function htmlFooter()
{	?>
	<h5>Judges Test On-line<br />
	Copyright © 2011  HRC, Inc.. All rights reserved. <br />
	Revised:
	<!--WEBBOT bot=TimeStamp      S-Type="EDITED"      S-Format="%B %d, %Y" startspan  -->
	January   1, 2013</h5>
	<!-- InstanceEndEditable --></td>
		</tr>
		</table></td>
	</tr>
	<tr>
		<td height="3" bgcolor="#000000" id="BlackBackground">&nbsp;</td>
	</tr>
	<tr>
		<td height="3" align="center" bgcolor="#6F0202">
		<!--#include file="bottomfeeder.shtml" -->
		<?php
		include("bottomfeeder.shtml");
		?>
		</td>
	</tr>
	</table>
	</body>
	<!-- InstanceEnd --></html>
<?php
}
//******************************************************************************
function logUser($mbrName, $mbrNumber, $mbrEmail, $passFail, $message)
{   if (!file_exists("JudgeTESTusersLog.txt"))
    {  $logHandle = fopen("JudgeTESTusersLog.txt", 'a'); //append
        if ($logHandle)
        {   $record = "Date & Time, Member's Name, HRC Number, Email, ";
            $record .= "User's IP Address, Pass or Fail, (Error Message)\n";
            fwrite($logHandle, $record);
        }
        else
        {   echo "<p>Error opening log file</p>";  
            exit;
        }
    }
    else
    {   $logHandle = fopen("JudgeTESTusersLog.txt", 'a'); }//append  

    if ($logHandle)
    {   $record = date("F j, Y, g:i a") . ", " .
                  $mbrName . ", " .
                  $mbrNumber . ", " .
                  $mbrEmail . ", " . 
                  //IP address from which the user is viewing the current page.
                  $_SERVER['REMOTE_ADDR'] . ", " .
				  $passFail;
         if (isset($message))
         {  $record .= ", " . $message; }
         $record .= "\n";
         fwrite($logHandle, $record);
         fclose($logHandle);
    }
    else
    {   echo "<p>Error opening log file</p>";  }
} //end logUser function
//**************************************************************************
function emailLetter($inputNum)
//returns "AA", "AB"..., "BA", "BB",..., "CA", "CB"...
{	$newNum = $inputNum +  64;
	$int = intval($newNum / 91);
	return chr($int + 65) . chr($newNum - ($int * 26));
}
?>